<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    {{-- Chrome prints from a page it renders offline, with no dev server and no
         base URL to resolve a stylesheet against, so everything is inline. --}}
    <style>
        * { box-sizing: border-box; }

        body {
            margin: 0;
            font-family: Helvetica, Arial, sans-serif;
            font-size: 9px;
            line-height: 1.45;
            color: #0f172a;
        }

        .masthead {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            gap: 24px;
            padding-bottom: 10px;
            border-bottom: 2px solid #0f172a;
        }

        .issuer-name { margin: 0; font-size: 15px; font-weight: 800; letter-spacing: -0.02em; }

        .doc-kind { text-align: right; }
        .doc-kind h2 { margin: 0; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; }
        .doc-kind p { margin: 3px 0 0; font-size: 8.5px; color: #475569; }

        table.rows {
            width: 100%;
            margin-top: 14px;
            border-collapse: collapse;
        }

        table.rows th,
        table.rows td {
            padding: 5px 7px;
            border-bottom: 1px solid #e2e8f0;
            text-align: left;
            vertical-align: top;
            word-break: break-word;
        }

        table.rows thead th {
            font-size: 8px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            color: #475569;
            background: #f8fafc;
            border-bottom: 1px solid #cbd5e1;
        }

        /* A row that lands on a page break is otherwise split in half, and the
           heading repeats itself on every page because `thead` is a header. */
        table.rows tr { page-break-inside: avoid; }
        table.rows thead { display: table-header-group; }

        .empty { margin-top: 18px; font-size: 10px; color: #64748b; }

        .colophon {
            margin-top: 18px;
            padding-top: 8px;
            border-top: 1px solid #e2e8f0;
            font-size: 8px;
            color: #64748b;
        }
    </style>
</head>
<body>
    <header class="masthead">
        <h1 class="issuer-name">{{ $issuer }}</h1>

        <div class="doc-kind">
            <h2>{{ $title }}</h2>
            @if ($subtitle !== '')
                <p>{{ $subtitle }}</p>
            @endif
            <p>Generated {{ $issued_at }}</p>
            <p>{{ count($rows) }} {{ Str::plural('row', count($rows)) }}</p>
        </div>
    </header>

    @if (count($rows) === 0)
        <p class="empty">Nothing matched the window this was run for.</p>
    @else
        <table class="rows">
            <thead>
                <tr>
                    @foreach ($headings as $heading)
                        <th>{{ $heading }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <footer class="colophon">
        Generated by {{ $issuer }} on {{ $issued_at }}. This document lists exactly the rows
        the same export produces as CSV and Excel.
    </footer>
</body>
</html>
